language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - build-tools-25.0.0
    - android-25
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew :cleaninsights-piwik-sdk:assemble :cleaninsights-piwik-sdk:testDebugUnitTest

after_success: ./gradlew :cleaninsights-piwik-sdk:jacocoTestReport :cleaninsights-piwik-sdk:coveralls
